<?php
    $helper = Mage::helper('widgetcontacts');
    $geoData = $helper->getGeoData();
?>

<div class="company-contacts-page">
    <div class="company-contacts-info">
    <?php
        $filter = Mage::getModel('widget/template_filter');
        $widget = $filter->filter('{{widget type="widgetcontacts/widget"}}');
        echo $widget;
    ?>
    </div>
    <div id="company-contacts-map"></div>
</div>
<script type="text/javascript">
    function initMap() {
        let pos = {lng: <?php echo $geoData['0'];?>, lat: <?php echo $geoData['1'];?>};
        let opt = {
            center: pos,
            zoom: 16.5
        };

        let map = new google.maps.Map(document.getElementById('company-contacts-map'), opt);
        let marker = new google.maps.Marker({
            map: map,
            position: pos,
            title: 'We here!'
        });

        let info = new google.maps.InfoWindow({
            content: '<?php echo $widget; ?>',
        });
        
        marker.addListener("click", function () {
            info.open(map, marker);
        })
    }
</script>
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBCtSQcFe4O2TuU1L54_k96Kr0H0qpv_Ng&callback=initMap"
        async defer></script>
